### ISSUE TITLE
Ros 2 timestamp conversion issue with Euroc Dataset

### ISSUE THREAD

**Issue by geoeo** [aau-cns/MSCEqF#12]
Hello,

I was able to create a simple launch file and run MSCEqF however, there seems to be a timestamp conversion issue.

My launch is as follows:

```
from launch import LaunchDescription

import launch.actions
import launch_ros.actions

bag_path = '/euroc/bags/MH_01_easy'
bag_start_offset = '50'

def generate_launch_description():
    return LaunchDescription([
        launch_ros.actions.Node(
            package='msceqf',
            executable='msceqf_ros2',
            name='msceqf_ros2',
            output='screen',
            parameters=[
                {'config_filepath': '/workspaces/examples/euroc/config/config.yaml'},
                {'imu_topic': '/imu0'},
                {'cam_topic': '/cam0/image_raw'},
                ],            
        ),
        launch.actions.ExecuteProcess(
            cmd=['ros2', 'bag', 'play',
                f'{bag_path}',
                '--start-offset',
                f'{bag_start_offset}', 
                ],
            output='log'
        )
])
```

When I run it as is I get:

```
[msceqf_ros2-1] -9.99881e-05  1.49672e-06  3.75619e-11            0            0            0            0            0            0 -1.06062e-07 -7.08519e-06 -9.10785e-06  8.88873e-07   5.9381e-05 -6.44214e-07   9.6804e-09  0.000999999 -3.75454e-07  8.13223e-07  2.44102e-08   6.5224e-06
[msceqf_ros2-1]   4.1403e-07  2.57155e-06  9.99661e-09            0            0            0            0            0            0 -1.83118e-07  3.02595e-08 -1.99835e-07  1.52692e-06 -2.60289e-07  3.71721e-06  2.57631e-06 -3.75454e-07  0.000900078 -4.63584e-09 -2.58279e-08  2.88579e-08
[msceqf_ros2-1] -8.13937e-07 -4.11921e-08 -2.06691e-10            0            0            0  1.48655e-10  9.99557e-09 -2.57744e-10  2.93743e-09  -5.7695e-08 -6.92223e-08 -2.44574e-08   4.8368e-07 -8.21589e-08 -5.32681e-08  8.13223e-07 -4.63584e-09  0.000900017  7.31417e-10  5.19378e-08
[msceqf_ros2-1] -3.89778e-08 -9.72828e-07 -6.49932e-10            0            0            0 -9.99881e-09  1.49672e-10  3.75619e-11  6.89932e-08 -2.82188e-09  8.61527e-08 -5.77726e-07  2.40847e-08 -1.40294e-06  -9.7296e-07  2.44102e-08 -2.58279e-08  7.31417e-10   0.00090002 -1.85544e-08
[msceqf_ros2-1] -6.49073e-06  2.16734e-06 -2.88706e-12            0            0            0   4.1403e-11  2.57155e-10  9.99661e-09 -1.53578e-07 -4.59936e-07 -7.82011e-07  1.28714e-06  3.85473e-06  2.94132e-06  2.06989e-06   6.5224e-06  2.88579e-08  5.19378e-08 -1.85544e-08  0.000900478.
[msceqf_ros2-1] terminate called after throwing an instance of 'std::runtime_error'
[msceqf_ros2-1]   what():  Time is out of dual 32-bit range
[ERROR] [msceqf_ros2-1]: process has died [pid 93588, exit code -6, cmd '/workspaces/install/msceqf/lib/msceqf/msceqf_ros2 --ros-args -r __node:=msceqf_ros2 --params-file /tmp/launch_params_5ln4wpic --params-file /tmp/launch_params_6d8eq35u --params-file /tmp/launch_params_9kjeom8r'].
```

So I made the following changes:

```
  static rclcpp::Time fromSec(double t)
  {
    // int64_t sec64 = static_cast<int64_t>(floor(t));
    // if (sec64 < 0 || sec64 > std::numeric_limits<uint32_t>::max())
    //   throw std::runtime_error("Time is out of dual 32-bit range");
    // uint32_t sec = static_cast<uint32_t>(sec64);
    // uint32_t nsec = static_cast<uint32_t>(std::round((t - sec) * 1e9));
    // sec += (nsec / 1000000000ul);
    // nsec %= 1000000000ul;
    // return rclcpp::Time(sec, nsec);

    const auto sec = std::chrono::duration<double>(t);
    const auto nsec = std::chrono::duration_cast<std::chrono::nanoseconds>(sec);
    return rclcpp::Time(nsec.count());
  }

```

But then I get this behaviour
```


2.57631e-06 -3.75454e-07  0.000900078 -4.63584e-09 -2.58279e-08  2.88579e-08
[msceqf_ros2-1] -8.13937e-07 -4.11921e-08 -2.06691e-10            0            0            0  1.48655e-10  9.99557e-09 -2.57744e-10  2.93743e-09  -5.7695e-08 -6.92223e-08 -2.44574e-08   4.8368e-07 -8.21589e-08 -5.32681e-08  8.13223e-07 -4.63584e-09  0.000900017  7.31417e-10  5.19378e-08
[msceqf_ros2-1] -3.89778e-08 -9.72828e-07 -6.49932e-10            0            0            0 -9.99881e-09  1.49672e-10  3.75619e-11  6.89932e-08 -2.82188e-09  8.61527e-08 -5.77726e-07  2.40847e-08 -1.40294e-06  -9.7296e-07  2.44102e-08 -2.58279e-08  7.31417e-10   0.00090002 -1.85544e-08
[msceqf_ros2-1] -6.49073e-06  2.16734e-06 -2.88706e-12            0            0            0   4.1403e-11  2.57155e-10  9.99661e-09 -1.53578e-07 -4.59936e-07 -7.82011e-07  1.28714e-06  3.85473e-06  2.94132e-06  2.06989e-06   6.5224e-06  2.88579e-08  5.19378e-08 -1.85544e-08  0.000900478.
[msceqf_ros2-1] [ ERROR]: No IMU readings in between 913555501403636608.000000 and 963555501403636608.000000.
[msceqf_ros2-1] [ ERROR]: Unable to propagate. Empty propagation buffer.
[msceqf_ros2-1] [ ERROR]: Propagation failure.
[msceqf_ros2-1] [ WARNING]: Received IMU measurement older than actual state estimate. Discarding measurement.
[msceqf_ros2-1] [ WARNING]: Received IMU measurement older than actual state estimate. Discarding measurement.
[msceqf_ros2-1] [ WARNING]: Received IMU measurement older than actual state estimate. Discarding measurement.
[msceqf_ros2-1] [ WARNING]: Received IMU measurement older than actual state estimate. Discarding measurement.
```

Do the timestamps somehow get realigned in the code?

**Comment by AlessandroFornasier** [comment]
Hi,

I think I had a similar issue in the past. Let me have a look,

**Comment by geoeo** [comment]
Thanks for your help @AlessandroFornasier

**Comment by AlessandroFornasier** [comment]
Can you pull `fix/ros2` and give it a try?

I just went a simple route of converting the time to nanoseconds and casting into a `uint64_t` before constructing `rclcpp::Time`

**Comment by geoeo** [comment]
Hey, so I tried it and now I get the following error

```
078 -4.63584e-09 -2.58279e-08  2.88579e-08
[msceqf_ros2-1] -8.13937e-07 -4.11921e-08 -2.06691e-10            0            0            0  1.48655e-10  9.99557e-09 -2.57744e-10  6.53113e-09 -1.29022e-07 -6.04512e-09  1.17923e-08 -2.32817e-07 -3.85104e-08 -5.32681e-08  8.13223e-07 -4.63584e-09  0.000900017  7.31417e-10  5.19378e-08
[msceqf_ros2-1] -3.89778e-08 -9.72828e-07 -6.49932e-10            0            0            0 -9.99881e-09  1.49672e-10  3.75619e-11   1.5418e-07 -6.27891e-09  1.51873e-07  2.78128e-07 -1.16537e-08  7.63539e-07  -9.7296e-07  2.44102e-08 -2.58279e-08  7.31417e-10   0.00090002 -1.85544e-08
[msceqf_ros2-1] -6.49073e-06  2.16734e-06 -2.88706e-12            0            0            0   4.1403e-11  2.57155e-10  9.99661e-09 -3.43471e-07 -1.02863e-06 -4.39379e-07 -6.19508e-07  -1.8553e-06 -2.27471e-06  2.06989e-06   6.5224e-06  2.88579e-08  5.19378e-08 -1.85544e-08  0.000900478.
[msceqf_ros2-1] [ ERROR]: No IMU readings in between 113555501403636624.000000 and 163555501403636640.000000.
[msceqf_ros2-1] [ ERROR]: Unable to propagate. Empty propagation buffer.
[msceqf_ros2-1] [ ERROR]: Propagation failure.
[msceqf_ros2-1] [ WARNING]: No valid features to update with. Skipping update step.
[msceqf_ros2-1] [ WARNING]: Failed update..
[msceqf_ros2-1] [ WARNING]: No valid features to update with. Skipping update step.
[msceqf_ros2-1] [ WARNING]: Failed update..
[msceqf_ros2-1] [ WARNING]: No valid features to update with. Skipping update step.
[msceqf_ros2-1] [ WARNING]: Failed update..
[msceqf_ros2-1] terminate called after throwing an instance of 'std::out_of_range'
[msceqf_ros2-1]   what():  map::at
```

Ill recompile in debug and try to get you some better debug output

In Debug mode I get
```

223e-07 -4.63584e-09  0.000900017  7.31417e-10  5.19378e-08
-3.89778e-08 -9.72828e-07 -6.49932e-10            0            0            0 -9.99881e-09  1.49672e-10  3.75619e-11  6.89932e-08 -2.82188e-09  8.61527e-08 -5.77726e-07  2.40847e-08 -1.40294e-06  -9.7296e-07  2.44102e-08 -2.58279e-08  7.31417e-10   0.00090002 -1.85544e-08
-6.49073e-06  2.16734e-06 -2.88706e-12            0            0            0   4.1403e-11  2.57155e-10  9.99661e-09 -1.53578e-07 -4.59936e-07 -7.82011e-07  1.28714e-06  3.85473e-06  2.94132e-06  2.06989e-06   6.5224e-06  2.88579e-08  5.19378e-08 -1.85544e-08  0.000900478.
[ ERROR]: No IMU readings in between 913555501403636608.000000 and 963555501403636608.000000.
[ ERROR]: Unable to propagate. Empty propagation buffer.
[ ERROR]: Propagation failure.
[ WARNING]: Received IMU measurement older than actual state estimate. Discarding measurement.
[ WARNING]: Received IMU measurement older than actual state estimate. Discarding measurement.
[ WARNING]: Received IMU measurement older than actual state estimate. Discarding measurement.
[ WARNING]: Received IMU measurement older than actual state estimate. Discarding measurement.
[ WARNING]: Received IMU measurement older than actual state estimate. Discarding measurement.
[ WARNING]: Received IMU measurement older than actual state estimate. Discarding measurement.
```
If you tell me where to look I can set breakpoints there and post relevant state information

**Comment by TannerGilbert** [comment]
Hey @geoeo I ran into the same problem when trying to run on a custom dataset in ROS2. I fixed it by changing the timestep calculation in `callback_image´ and `callback_imu` (see #13).

**Comment by geoeo** [comment]
Thanks a lot @TannerGilbert ill have a look some time this week!

**Comment by AlessandroFornasier** [comment]
Hi, sorry for my absence, I was quite busy lately. Thanks @TannerGilbert I have merged your PR.

I will wait @geoeo to try it out before merging `fix/ros2`

**Comment by geoeo** [comment]
I tried it but it still crashed with 

```
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Created System State element [Extended Pose (T)].
[msceqf_ros2-1] [ INFO]: Created System State element [Bias (b)].
[msceqf_ros2-1] [ INFO]: Created System State element [Extrinsic Camera Calibration (S)].
[msceqf_ros2-1] [ INFO]: Created MSCEqF State element [Semi Direct Bias (D, delta)].
[msceqf_ros2-1] [ INFO]: Created MSCEqF State element [Special Euclidean (E)].
[msceqf_ros2-1] [ INFO]: Origin set to:
[msceqf_ros2-1] T0:
[msceqf_ros2-1]     0.401723  -0.00811146     0.915725            0            0
[msceqf_ros2-1] -3.59652e-19    -0.999961  -0.00885761            0            0
[msceqf_ros2-1]     0.915761    0.0035583    -0.401707            0            0
[msceqf_ros2-1]            0            0            0            1            0
[msceqf_ros2-1]            0            0            0            0            1
[msceqf_ros2-1] b0:
[msceqf_ros2-1] -0.00693943   0.0791123   0.0352557     1.61647  0.00628099   -0.709079
[msceqf_ros2-1] S0:
[msceqf_ros2-1]  0.0148655  -0.999881  0.0041403 -0.0216401
[msceqf_ros2-1]   0.999557  0.0149672  0.0257155  -0.064677
[msceqf_ros2-1] -0.0257744 0.00375619   0.999661 0.00981073
[msceqf_ros2-1]          0          0          0          1
[msceqf_ros2-1] Set initial MSCEqF core state to
[msceqf_ros2-1] D:
[msceqf_ros2-1] 1 0 0 0 0
[msceqf_ros2-1] 0 1 0 0 0
[msceqf_ros2-1] 0 0 1 0 0
[msceqf_ros2-1] 0 0 0 1 0
[msceqf_ros2-1] 0 0 0 0 1
[msceqf_ros2-1] delta:
[msceqf_ros2-1] 0 0 0 0 0 0
[msceqf_ros2-1] E:
[msceqf_ros2-1] 1 0 0 0
[msceqf_ros2-1] 0 1 0 0
[msceqf_ros2-1] 0 0 1 0
[msceqf_ros2-1] 0 0 0 1
[msceqf_ros2-1] Initial time: 1.40364e+09
[msceqf_ros2-1] Set initial MSCEqF covariance to:
[msceqf_ros2-1]       0.0001            0            0            0            0            0            0            0            0            0  3.52557e-06 -7.91123e-06            0 -7.09079e-05 -6.28099e-07  1.48655e-06 -9.99881e-05   4.1403e-07 -8.13937e-07 -3.89778e-08 -6.49073e-06
[msceqf_ros2-1]            0       0.0001            0            0            0            0            0            0            0 -3.52557e-06            0 -6.93943e-07  7.09079e-05            0  0.000161647  9.99557e-05  1.49672e-06  2.57155e-06 -4.11921e-08 -9.72828e-07  2.16734e-06
[msceqf_ros2-1]            0            0        1e-08            0            0            0            0            0            0  7.91123e-10  6.93943e-11            0  6.28099e-11 -1.61647e-08            0 -2.57744e-10  3.75619e-11  9.99661e-09 -2.06691e-10 -6.49932e-10 -2.88706e-12
[msceqf_ros2-1]            0            0            0       0.0001            0            0            0            0            0            0            0            0            0  3.52557e-06 -7.91123e-06            0            0            0            0            0            0
[msceqf_ros2-1]            0            0            0            0       0.0001            0            0            0            0            0            0            0 -3.52557e-06            0 -6.93943e-07            0            0            0            0            0            0
[msceqf_ros2-1]            0            0            0            0            0       0.0001            0            0            0            0            0            0  7.91123e-06  6.93943e-07            0            0            0            0            0            0            0
[msceqf_ros2-1]            0            0            0            0            0            0        1e-08            0            0            0            0            0            0            0            0            0            0            0  1.48655e-10 -9.99881e-09   4.1403e-11
[msceqf_ros2-1]            0            0            0            0            0            0            0        1e-08            0            0            0            0            0            0            0            0            0            0  9.99557e-09  1.49672e-10  2.57155e-10
[msceqf_ros2-1]            0            0            0            0            0            0            0            0        1e-08            0            0            0            0            0            0            0            0            0 -2.57744e-10  3.75619e-11  9.99661e-09
[msceqf_ros2-1]            0 -3.52557e-06  7.91123e-10            0            0            0            0            0            0  0.000100124  5.48994e-12  2.44654e-08  -2.4999e-06 -1.27883e-09 -5.69897e-06 -3.52402e-06 -5.27649e-08 -8.98709e-08   1.4359e-09  3.42463e-08 -7.64113e-08
[msceqf_ros2-1]  3.52557e-06            0  6.93943e-11            0            0            0            0            0            0  5.48994e-12  0.000100124 -2.78916e-07  4.35865e-13 -2.50002e-06  -2.2144e-08  5.24077e-08 -3.52515e-06  1.46663e-08 -2.86973e-08  -1.3787e-09 -2.28835e-07
[msceqf_ros2-1] -7.91123e-06 -6.93943e-07            0            0            0            0            0            0            0  2.44654e-08 -2.78916e-07  0.000100631  -4.9206e-07  5.60969e-06 -1.07205e-06  -8.1124e-07   7.8999e-06 -5.05999e-08  6.46783e-08  9.83449e-09  4.98457e-07
[msceqf_ros2-1]            0  7.09079e-05  6.28099e-11            0 -3.52557e-06  7.91123e-06            0            0            0  -2.4999e-06  4.35865e-13  -4.9206e-07  0.000151029  5.47979e-08  0.000114645  7.08765e-05  1.06129e-06   1.8235e-06 -2.92097e-08 -6.89816e-07  1.53682e-06
[msceqf_ros2-1] -7.09079e-05            0 -1.61647e-08  3.52557e-06            0  6.93943e-07            0            0            0 -1.27883e-09 -2.50002e-06  5.60969e-06  5.47979e-08  0.000150435  1.66456e-07 -1.05367e-06  7.08994e-05 -3.09739e-07   5.7748e-07   2.8689e-08  4.60245e-06
[msceqf_ros2-1] -6.28099e-07  0.000161647            0 -7.91123e-06 -6.93943e-07            0            0            0            0 -5.69897e-06  -2.2144e-08 -1.07205e-06  0.000114645  1.66456e-07  0.000361932  0.000161566  3.04743e-06  4.15424e-06 -6.14734e-08  -1.5723e-06  3.54421e-06
[msceqf_ros2-1]  1.48655e-06  9.99557e-05 -2.57744e-10            0            0            0            0            0            0 -3.52402e-06  5.24077e-08  -8.1124e-07  7.08765e-05 -1.05367e-06  0.000161566  0.000999934   9.6804e-09  2.57631e-06 -5.32681e-08  -9.7296e-07  2.06989e-06
[msceqf_ros2-1] -9.99881e-05  1.49672e-06  3.75619e-11            0            0            0            0            0            0 -5.27649e-08 -3.52515e-06   7.8999e-06  1.06129e-06  7.08994e-05  3.04743e-06   9.6804e-09  0.000999999 -3.75454e-07  8.13223e-07  2.44102e-08   6.5224e-06
[msceqf_ros2-1]   4.1403e-07  2.57155e-06  9.99661e-09            0            0            0            0            0            0 -8.98709e-08  1.46663e-08 -5.05999e-08   1.8235e-06 -3.09739e-07  4.15424e-06  2.57631e-06 -3.75454e-07  0.000900078 -4.63584e-09 -2.58279e-08  2.88579e-08
[msceqf_ros2-1] -8.13937e-07 -4.11921e-08 -2.06691e-10            0            0            0  1.48655e-10  9.99557e-09 -2.57744e-10   1.4359e-09 -2.86973e-08  6.46783e-08 -2.92097e-08   5.7748e-07 -6.14734e-08 -5.32681e-08  8.13223e-07 -4.63584e-09  0.000900017  7.31417e-10  5.19378e-08
[msceqf_ros2-1] -3.89778e-08 -9.72828e-07 -6.49932e-10            0            0            0 -9.99881e-09  1.49672e-10  3.75619e-11  3.42463e-08  -1.3787e-09  9.83449e-09 -6.89816e-07   2.8689e-08  -1.5723e-06  -9.7296e-07  2.44102e-08 -2.58279e-08  7.31417e-10   0.00090002 -1.85544e-08
[msceqf_ros2-1] -6.49073e-06  2.16734e-06 -2.88706e-12            0            0            0   4.1403e-11  2.57155e-10  9.99661e-09 -7.64113e-08 -2.28835e-07  4.98457e-07  1.53682e-06  4.60245e-06  3.54421e-06  2.06989e-06   6.5224e-06  2.88579e-08  5.19378e-08 -1.85544e-08  0.000900478.
[msceqf_ros2-1] [ ERROR]: No IMU readings in between 1403636584.413555 and 1403636584.463556.
[msceqf_ros2-1] [ ERROR]: Unable to propagate. Empty propagation buffer.
[msceqf_ros2-1] [ ERROR]: Propagation failure.
[msceqf_ros2-1] terminate called after throwing an instance of 'std::out_of_range'
[msceqf_ros2-1]   what():  map::at
```

I also tried with MH_01_easy MH_02_easy and V1_01_easy.  If you have some bags which are known to work I would be happy to try them out

**Comment by TannerGilbert** [comment]
Hey @geoeo I just tried running MSCEqF on the `V1_01_easy` and it worked without the error above. Both my devices run Ubuntu 22.04 and ROS 2 Humble.

Used command:
```
ros2 run msceqf msceqf_ros2 --ros-args \                                                                                                                                                                    
  -p config_filepath:="euroc_config.yaml" \
  -p imu_topic:="/imu0" \
  -p cam_topic:="/cam0/image_raw"
```

with `euroc_config.yaml` from the [example folder](https://github.com/aau-cns/MSCEqF/blob/main/examples/euroc/config/config.yaml).

**Comment by geoeo** [comment]
@TannerGilbert Interesting. Would you mind trying inside of the Docker container? Afaik it runs on ros iron

**Comment by TannerGilbert** [comment]
@geoeo I just tried it in the [provided ROS Iron Dockercontainer](https://github.com/aau-cns/MSCEqF/blob/main/docker/Dockerfile_ros2) and was able to run it. You can find the commands I used below:

Build (from msceqf folder9:
```
docker build --network=host -t msceqf:ros2 -f docker/Dockerfile_ros2 .
```

Run:
```
docker run --net=host -it --gpus all --env="NVIDIA_DRIVER_CAPABILITIES=all" --env="DISPLAY" --env="QT_X11_NO_MITSHM=1" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" msceqf:ros$ROS_VERSION .
```

Inside container (build, download and convert bag and then run MSCeqF):
```bash
colcon build --event-handlers console_cohesion+ --cmake-args -DCMAKE_BUILD_TYPE=Release --cmake-args -DROS_BUILD=ON
sudo apt install wget python3-pip
wget http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_01_easy/V1_01_easy.bag
pip3 install rosbags
rosbags-convert --src V1_01_easy.bag --dst V1_01_easy
wget https://raw.githubusercontent.com/aau-cns/MSCEqF/refs/heads/main/examples/euroc/config/config.yaml
ros2 run msceqf msceqf_ros2 --ros-args -p config_filepath:="config.yaml" -p imu_topic:="/imu0" -p cam_topic:="/cam0/image_raw"
ros2 bag play V1_01_easy --clock # Run in a second terminal
```

For reference I used a branch of my own fork with one additional commit but it shouldn't change anything as this is only to make it build with GCC 9 (https://github.com/TannerGilbert/MSCEqF/tree/fix/basic_stream_error)

**Comment by geoeo** [comment]
Ok @TannerGilbert then ill try again with these commands! Thanks

**Comment by geoeo** [comment]
@TannerGilbert You are absolutely correct. When I launch the node in a terminal and then launch the bag in another it works! I do get the initial errors but no exception 

```
-3.89778e-08 -9.72828e-07 -6.49932e-10            0            0            0 -9.99881e-09  1.49672e-10  3.75619e-11  7.59914e-08 -3.04682e-09   3.1568e-09  9.73834e-09 -4.06139e-10  2.38854e-08  -9.7296e-07  2.44102e-08 -2.58279e-08  7.31417e-10   0.00090002 -1.85544e-08
-6.49073e-06  2.16734e-06 -2.88706e-12            0            0            0   4.1403e-11  2.57155e-10  9.99661e-09 -1.69329e-07 -5.07103e-07  1.24549e-07 -2.16953e-08 -6.49728e-08 -5.58816e-08  2.06989e-06   6.5224e-06  2.88579e-08  5.19378e-08 -1.85544e-08  0.000900478.
[ ERROR]: No IMU readings in between 1403715273.712143 and 1403715273.762143.
[ ERROR]: Unable to propagate. Empty propagation buffer.
[ ERROR]: Propagation failure.
[ ERROR]: No IMU readings in between 1403715273.712143 and 1403715273.812143.
[ ERROR]: Unable to propagate. Empty propagation buffer.
[ ERROR]: Propagation failure.
[ INFO]: Successful zero velocity update.
[ INFO]: Successful zero velocity update.
[ INFO]: Successful zero velocity update.
[ INFO]: Successful zero velocity update.
[ INFO]: Successful zero velocity update.
[ INFO]: Successful zero velocity update.
...

[ INFO]: Successful update with 27 tracks.
[ INFO]: Successful update with 14 tracks.
[ WARNING]: No valid features to update with. Skipping update step.
[ WARNING]: Failed update..
[ WARNING]: No valid features to update with. Skipping update step.
[ WARNING]: Failed update..
[ INFO]: Successful update with 1 tracks.
[ WARNING]: No valid features to update with. Skipping update step.
[ WARNING]: Failed update..
[ INFO]: Successful update with 1 tracks.
[ WARNING]: No valid features to update with. Skipping update step.
[ WARNING]: Failed update..
[ INFO]: Successful update with 52 tracks.
[ INFO]: Successful update with 46 tracks.
[ WARNING]: No valid features to update with. Skipping update step.
[ WARNING]: Failed update..
[ INFO]: Successful update with 27 tracks.
[ INFO]: Successful update with 14 tracks.
[ WARNING]: No valid features to update with. Skipping update step.
[ WARNING]: Failed update..
```

However when I run the project from a launch file it crashes! Even when I start the bag with a delay.

It seems to want to do some static initialization from the start?

```
msceqf_ros2-1] [ INFO]: Collecting IMU measurements for static initialization.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
[msceqf_ros2-1] [ INFO]: Not enough imu measurement for acceleration check in static initializer.
```
Could you try and run it with the following launch file? (This is from within the docker)

```
from launch import LaunchDescription

import launch.actions
import launch_ros.actions

bag_path = '/euroc/bags/V1_01_easy'
bag_start_offset = '0'
bag_delay = '10'

def generate_launch_description():
    return LaunchDescription([
        launch_ros.actions.Node(
            package='msceqf',
            executable='msceqf_ros2',
            name='msceqf_ros2',
            output='screen',
            parameters=[
                {'config_filepath': '/workspaces/examples/euroc/config/config.yaml'},
                {'imu_topic': '/imu0'},
                {'cam_topic': '/cam0/image_raw'},
                ],            
        ),
        launch.actions.ExecuteProcess(
            cmd=['ros2', 'bag', 'play',
                f'{bag_path}',
                '--start-offset',
                f'{bag_start_offset}',
                '-d',
                f'{bag_delay}'
                ],
            output='log'
        )
])
```

You might have to change the ros2.cmake

```
...
add_library(${PROJECT_NAME}_lib SHARED ${lib_sources})
ament_target_dependencies(${PROJECT_NAME}_lib ${ament_libraries})
target_link_libraries(${PROJECT_NAME}_lib ${libs})
target_include_directories(${PROJECT_NAME}_lib PUBLIC ${include_dirs} wrappers/ros/ros2/include)
install(TARGETS ${PROJECT_NAME}_lib
  ARCHIVE DESTINATION lib
  LIBRARY DESTINATION lib
  RUNTIME DESTINATION bin
)
install(DIRECTORY ${include_dirs} wrappers/ros/ros2/include
        DESTINATION include
        FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp"
)
ament_export_include_directories(include)
ament_export_libraries(${PROJECT_NAME}_lib)

add_executable(msceqf_ros2 wrappers/ros/ros2/source/msceqf_ros_node.cpp)
ament_target_dependencies(msceqf_ros2 ${ament_libraries})
target_link_libraries(msceqf_ros2 ${PROJECT_NAME}_lib)
install(DIRECTORY wrappers/ros/ros2/launch DESTINATION share/${PROJECT_NAME})
install(TARGETS msceqf_ros2 DESTINATION lib/${PROJECT_NAME})

ament_package()
```

**Comment by AlessandroFornasier** [comment]
Is the config file used the same? Seems like zero velocity update is not active when launching via launchfile

**Comment by geoeo** [comment]
@AlessandroFornasier Ill check, but I'm pretty sure was using the same config each time. So if it was on or off it should be the same behavior

**Comment by geoeo** [comment]
This is the config. zero update is enabled
```

# Euroc Config

# Initial standard deviations (attitude, velocity, position, bias, extrinsics, instrinsics)
extended_pose_std: [1.0e-2, 1.0e-2, 1.0e-4, 1.0e-2, 1.0e-2, 1.0e-2, 1.0e-4, 1.0e-4, 1.0e-4]
bias_std: [1.0e-2, 1.0e-2, 1.0e-2, 1.0e-2, 1.0e-2, 1.0e-2]
extrinsics_std: [3.0e-2, 3.0e-2, 3.0e-2, 3.0e-2, 3.0e-2, 3.0e-2]
intrinsics_std: [1.0, 1.0, 1.0, 1.0]

# IMU noise statistics
accelerometer_noise_density: 2.0000e-3  
accelerometer_random_walk:   3.0000e-3
gyroscope_noise_density: 1.6968e-04
gyroscope_random_walk:   1.9393e-05

# Camera calibration
distortion_coeffs: [-0.28340811, 0.07395907, 0.00019359, 1.76187114e-05]
distortion_model: radtan
resolution: [752, 480]
intrinsics: [458.654, 457.296, 367.215, 248.375]
T_imu_cam:
 - [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975]
 - [0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768]
 - [-0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949]
 - [0.0, 0.0, 0.0, 1.0]

# Initializer
static_initializer_imu_window: 0.5
static_initializer_acc_threshold: 0.05

# Checker
checker_disparity_window: 0.5
checker_disparity_threshold: 2.0

# Propagator
state_transition_order: -1
imu_buffer_max_size: 1000

# Updater
refine_traingulation: true
feature_min_depth: 0.1
feature_max_depth: 20
feature_refinement_max_iterations: 20
feature_refinement_tollerance: 1e-10
measurement_projection_method: unit_plane
feature_representation: anchored_euclidean
pixel_standerd_deviation: 1.0
curvature_correction: true
zero_velocity_update: enabled

# State options
enable_camera_intrinsic_calibration: false
gravity: 9.81
num_clones: 11

# Tracker
equalization_method: histogram
optical_flow_pyramid_levels: 4
detector_pyramid_levels: 2
feature_detector: shi-tomasi
grid_x_size: 6
grid_y_size: 6
min_feature_pixel_distance: 10
min_features: 100
max_features: 100
fast_threshold: 20
shi_tomasi_quality_level: 0.8

# Track Manager
max_track_length: 200

# Logger level [0: Full, 1: INFO, 2: WARN, 3: ERR, 4: INACTIVE]
logger_level: 1
```

**Comment by AlessandroFornasier** [comment]
Yes the behaviour should be the same but without zero velocity update you would need to tune the accelerometer threshold, but that’s another story.

It’s wired anyway. I am afraid I might not have time today to reproduce the issue but let me try to sneak in some time on a evening during the week to try it out (I am working on this on my free time only).

For the very moment you could try to enable debug logging and see if there are more info
